services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: 'host'
    volumes:
      - /home/rtech-local/jellyfin/config:/config
      - /home/rtech-local/jellyfin/cache:/cache
      - type: bind
        source: /home/rtech-local/media
        target: /media
        read_only: false
      - type: bind
        source: /home/rtech-local/media2
        target: /media2
        read_only: false
    #! Made sure this is set to unless stopped
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'