services:
  loki:
    image: grafana/loki:2.4.0
    volumes:
      - /home/rtech-local/loki:/etc/loki
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml